### ISSUE TITLE
자습신청 성별 필터링

### ISSUE THREAD

**Issue by yoosion030** [Team-Ampersand/Dotori-client-v2#103]
<img width="446" alt="스크린샷 2023-04-03 오후 12 22 24" src="https://user-images.githubusercontent.com/80191860/229404151-e8b76e5d-a036-4b5b-850b-8dabef52a464.png">
자습신청에서 성별 필터링이 잘 작동하지 않는 것 같습니다. **여자**부분이 선택이 안돼요. 그리고 남자 선택 후 여자 선택을 하면 초기화가 됩니다.

**Comment by wjdalsths** [comment]
수정했습니다
