### ISSUE TITLE
비밀번호 변경

### ISSUE THREAD

**Issue by yoosion030** [Team-Ampersand/Dotori-client-v2#117]
<img width="671" alt="스크린샷 2023-04-04 오전 10 43 33" src="https://user-images.githubusercontent.com/80191860/229664923-bad91356-5a22-45e5-a4ea-f5c87fba7b49.png">
기존 비밀번호는 8~20이고 새로운 비밀번호는 9~20이 맞나요?

**Comment by kangkong0805** [comment]
새로운 비밀번호도 똑같이 8~20인데 오타인 듯 하네요 수정하겠습니다
