### ISSUE TITLE
기상 음악 2027년으로 해도 신청이 돼요.

### ISSUE THREAD

**Issue by SungGil-5125** [Team-Ampersand/Dotori-client-v2#123]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/82089918/229685869-40e30b2b-ae74-4fed-8517-e0e72d34d3fc.png">

2027년 4월 7일인가 기상 음악 신청 했는데 신청이 돼요. 왼쪽 리스트에도 신청 목록도 안뜨고 현재 날짜보다 과거, 미래 둘 다 신청을 막아야할거 같습니다.

**Comment by kangkong0805** [comment]
달력은 신청하는 날짜가 아니라 조회하는 날짜입니다;;

**Comment by SungGil-5125** [comment]
아... 아쉽네요(?)
