### ISSUE TITLE
🐞 [BUG] - <공지사항의 제목이 길어지면 잘려요!!>

### ISSUE THREAD

**Issue by SeoJumee** [Team-Ampersand/Dotori-client-v2#202]
### Summary

공지사항에서 제목이 긴 특정 글의 제목이 잘려요

### Reproduction steps

```bash
1. 공지사항페이지에서 2022년 05월 04일 17시 02분에 등록된 보건실 관련 글 클릭
```

### Screenshots

![](https://ifh.cc/g/BxZ0ft.png)

### Browsers

Chrome

### OS

Mac

**Comment by apnalkkamkkamhanjoon** [comment]
확인했습니다.
