### ISSUE TITLE
react-toastify CustomHooks화에 대한 의견

### ISSUE THREAD

**Issue by ImChang-gyu** [Team-Ampersand/Dotori-client-v2#64]
https://github.com/Team-Ampersand/Dotori-client-v2/blob/d7e2975095abcc3d305b92132aedde6b68e6e229/src/components/Common/atoms/Buttons/LogoutButton/index.tsx#L1-L12

이렇게 매번 사용할때마다 toast를 불러오는것보다 useToastify라는 customHooks를 만들어 type과 message를 받아 처리할 수 있게 하는건 어떨까?

**Comment by kangkong0805** [comment]
toast도 type과 message를 받고 있는 방식인데 toast option이 요구된다면 custom hooks 사용하는 것이 좋겠지만 현재 toastContainer로 관리하고 처리하고 있습니다. 그래서 toast에 대한 custom hook을 만들었을 때 향상된 효과를 보일 수 있을지 잘 모르겠습니다.

**Comment by ImChang-gyu** [comment]
이 내용은 어떻게 보면 당장의 효율성은 잘 모를 수 있겠지만 추후에 해당 라이브러리가 오래되어 버전업을 진행해야할때 custom hooks는 hooks내 파일만 수정하면 되기에 좀 더 효율적으로 유지보수를 할 수 있다는 장점은 잇을거 같아서 제안한거긴 한데 물론 당장은 필요없는 작업이고 이미 다 되어있는 부분이라 지금 당장은 아니더라도 추후에 해당 부분 고려해보면 괜찮을거 같아!

**Comment by kangkong0805** [comment]
거기까지 생각을 못했는데 그런 부분에서 고려할 필요가 있겠군요, 유지보수 할 때는 앞서 말씀드린 것을 생각해보면서 더 좋은 코드를 작성할 수 있게 개선하겠습니다. 피드백 감사합니다!
