### ISSUE TITLE
기상음악 신청을 할 수가 없어요

### ISSUE THREAD

**Issue by chanwoo00106** [Team-Ampersand/Dotori-client-v2#76]
## 개요

일요일에 기상음악 신청을 할 수가 없어요

## 문제

1. 기상음악 리스트를 가져올 때 나는 500에러
<img width="380" alt="스크린샷 2023-04-02 오후 10 22 13" src="https://user-images.githubusercontent.com/57276315/229355504-11907e6e-866d-41e9-b0db-26984bcea0f6.png">

2. 기상음악 신청을 할 수 없다고 하는 front
<img width="351" alt="image" src="https://user-images.githubusercontent.com/57276315/229355548-bdc14a05-8fb7-4891-bbde-58711d4c55a4.png">

3. 그런데 기상음악 신청은 성공함
<img width="431" alt="image" src="https://user-images.githubusercontent.com/57276315/229355630-c3b62542-f894-4669-a8da-88515834a957.png">

**Comment by kangkong0805** [comment]
202가 음악을 신청할 수 없는 요일이란 뜻입니다

**Comment by kangkong0805** [comment]
server가 수정되어 일요일에도 기상음악을 신청할 수 있도록 바뀌었습니다
