### ISSUE TITLE
공지사항 페이지가 이상해요

### ISSUE THREAD

**Issue by 100Seung-Min** [Team-Ampersand/Dotori-client-v2#82]
처음에는 날짜별 구분이 이루어지지 않지만, 새로고침 하면은 날짜별로 구분이 됩니다.
<img width="497" alt="스크린샷 2023-04-02 오후 11 07 35" src="https://user-images.githubusercontent.com/81063667/229358044-33788542-6829-46e6-85f5-7250e19c0ffb.png">
<img width="530" alt="스크린샷 2023-04-02 오후 11 07 50" src="https://user-images.githubusercontent.com/81063667/229358056-ccd7e518-f8de-45cb-ad2c-c72fc4d8b441.png">

**Comment by chanwoo00106** [comment]
추가로 스크롤 되는 문제도 해결해 주셨으면 좋겠어요
sidebar 아래 부분이 비어있어요

<img width="532" alt="image" src="https://user-images.githubusercontent.com/57276315/229359315-3aca64e2-be81-44c3-b796-5adb7e764208.png">
