### ISSUE TITLE
로그인 할 때 뒤에 @gsm.hs.kr은 지워지지 않았으면 좋을 것 같아요

### ISSUE THREAD

**Issue by 100Seung-Min** [Team-Ampersand/Dotori-client-v2#85]
<img width="427" alt="스크린샷 2023-04-02 오후 11 17 49" src="https://user-images.githubusercontent.com/81063667/229358594-738dbf88-8d3b-4277-8aff-e607965ed77b.png">

**Comment by HWANBINYOO** [comment]
수정했습니다
